# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-02 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='zipcode',
            field=models.CharField(default='440114', max_length=120),
        ),
    ]
